### ISSUE TITLE
Add version specifiers for dependencies

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Deep-Atlas#31]
Currently, we always assume the user gets the `HEAD` of the `main` branch of some of the dependencies.

**Positives**
* Newest features from dependencies can be used right away inside of this repo

**Downsides**
* Pip will always reclone the entire repo when we run `pip install`

IMO once things are relatively stable (no big changes to be made) we can start using version specifiers so that we
can give the user more flexibility and potentially allow them to get the dependencies from PyPI

**Comment by EmilieDel** [comment]
Closed with [6c0f0a3](https://github.com/BlueBrain/Deep-Atlas/commit/6c0f0a35f2da78b878fb438ceed34808c3f08c7b).
